#!/bin/bash

# Exit if any subcommand fails
set -e

# First things first, let's get Homebrew up and running
# so we can install everything we need within this script.
# Homebrew will set up the Apple command-line tools during the install process
# See http://brew.sh
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update

# Clone our devfiles if they have not been already
if [ ! -d  ~/.dev ]; then
  git clone  https://github.com/graysonwright/dev ~/.dev
fi

# Install the programs and applications defined in `~/.dev/Brewfile`
cd ~/.dev && brew bundle

# Add python support in NeoVim, required for a number of plugins
pip3 install neovim

# Link up configuration files
if [ ! -e ~/.config ]; then
  ln -s ~/.dev/config ~/.config
fi

# If there is not a virtual machine for our Docker host to run on,
# create one.
docker-machine ls -q | grep -q 'default' ||\
  docker-machine create --driver virtualbox default

# Set hostname before generating SSH keys
read -p "What is the hostname for this computer? (ENTER to skip) " hostname
[ -z "$hostname" ] || scutil --set HostName $hostname

if [ ! -d ~/.ssh ]; then
  ssh-keygen
fi
