
# Shortcuts for ssh
alias sshcse='ssh wrightg7@cse.msu.edu'
alias sshicpc='ssh -X grayson@icpc.cse.msu.edu'
alias sshstudio='ssh melindaw@melindawrightstudio.com'
alias sshta='ssh ta231010@cse.msu.edu'
alias sshcruise='ssh 435cruise3@cse.msu.edu'
alias sshacm='ssh acm@acm.cse.msu.edu'
alias sshorithena='ssh grayson@orithena.cas.msu.edu'
alias sshimac='ssh grayson@imac.devices.graysonwright.com'

# shortcuts -- every keystroke counts!
alias l='ls'
alias ll='ls -lF'
alias la='ls -A'
alias cls='clear; pwd; echo; ls'
alias cll='clear; pwd; echo; ll'
alias cla='clear; pwd; echo; la'
alias g='git'
alias git='hub'
alias glg='g lg | h; echo'
alias gls='clear; pwd; echo; ls; echo; git s'
alias h='head'
alias retag='ctags -R --exclude=.svnignore --exclude=.git --exclude=log --exclude=tmp *'
alias ag='ag -i'
alias flogit='find . -name \*.rb | xargs flog'
alias flayit='find . -name \*.rb | xargs flay'

# Notifications for after long-running jobs
alias notify='terminal-notifier -message "Task done!"; bell'
alias push='httparty -a post -r -d "token=AgWcEK3mj1BdXnhapJjz9mJDH18X1M&user=xn6H7TxUCGKTkJOviZxNFy4yMGv27b&title=Process+Finished&message=Put+down+that+beer" https://api.pushover.net/1/messages.json'

# Sleep the computer (OS X only)
alias sleep!='pmset sleepnow'

# Reloading config files
alias .a='. ~/.bash_aliases'
alias .b='. ~/.bash_profile ~/.bashrc'
# Editing config files
alias ..a='vi ~/.bash_aliases; .a'
alias ..b='vi ~/.bash_profile ~/.bashrc; .b'
alias ..g='vi ~/.gitconfig'

alias be='bundle exec'
alias ra='rake'
alias r='rails'
#alias rake='bundle exec rake'

# Keep track of device locations
alias devices='dnsimple record:list graysonwright.com'

# Helpful aliases
alias ip="curl --connect-timeout 5 icanhazip.com"
alias bell="echo -n $'\a'"
alias remake="make clean; cls; make"
alias mvi="mvim"

# Useful functions
function mkcd()
{
  mkdir $1
  cd $1
}

# Make things colorful!
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
