set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtimeath to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle, required
Bundle 'gmarik/vundle'

" Plugins, managed with vundle
Bundle 'tpope/vim-sensible'
Bundle 'tpope/vim-bundler'
Bundle 'tpope/vim-rails'
Bundle 'thoughtbot/vim-rspec'
Bundle 'altercation/vim-colors-solarized'
Bundle 'scrooloose/syntastic'
Bundle 'jeetsukumaran/vim-buffergator'
Bundle 'itchyny/lightline.vim'

Bundle 'kana/vim-textobj-user'
Bundle 'nelstrom/vim-textobj-rubyblock'

runtime macros/matchit.vim


let mapleader=" "

syntax on
filetype plugin indent on

colorscheme solarized
set background=light

" Fast editing of .vimrc file
map <Leader>v :e ~/.vimrc<CR>
autocmd! bufwritepost .vimrc source %

" Fast editing of ~/tools.md file
map <Leader>t :e ~/tools.md<CR>

" Fast movement within a file
set relativenumber

" Use 2 spaces as a tab
set expandtab
set tabstop=2
set shiftwidth=2

" Quickly open/close buffers
map <Leader>w :w<CR>
map <Leader>q :q<CR>
map <Leader>d :bd<CR>
map <Leader>j :bn<CR>
map <Leader>k :bp<CR>

" Better searching
set hlsearch
set ignorecase
set smartcase

" Open split windows
set splitbelow
set splitright
noremap <C-Down> :sp<CR>
noremap <C-Up> :sp<CR><C-W><C-K>
noremap <C-Right> :vsp<CR>
noremap <C-Left> :vsp<CR><C-W><C-H>

" Navigate split windows
noremap <C-J> <C-W><C-J>
noremap <C-K> <C-W><C-K>
noremap <C-L> <C-W><C-L>
noremap <C-H> <C-W><C-H>

" Allow buffers to be backgrounded
" even if they have unsaved changes
set hidden

" RSpec.vim mappings
if executable("spring")
  let g:rspec_command = "!spring rspec {spec}"
endif
map <Leader>sf :call RunCurrentSpecFile()<CR>
map <Leader>ss :call RunNearestSpec()<CR>
map <Leader>sl :call RunLastSpec()<CR>
map <Leader>sa :call RunAllSpecs()<CR>

" Open files
map <Leader>o :!open %<CR>

" Quicker opening and closing of folds
" TODO automatic folds based on filetype
map <Leader><Space> za

" TODO map capital U to 'redo' (ctrl-r)

" Mark long lines
"highlight OverLength ctermbg=red ctermfg=white guibg=#592929
"match OverLength /\%81v.\+/
set colorcolumn=81

" Quickly toggle paste mode
nnoremap <Leader>p :set invpaste paste?<CR>

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif

" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>
