let mapleader=" "

execute pathogen#infect()
syntax on
filetype plugin indent on

colorscheme solarized
set background=light

" Fast editing of .vimrc file
map <Leader>v :e ~/.vimrc<CR>
autocmd! bufwritepost .vimrc source %

" Fast movement within a file
set relativenumber

" Use 2 spaces as a tab
set expandtab
set tabstop=2
set shiftwidth=2

" Quickly open/close buffers
map <Leader>w :w<CR>
map <Leader>q :q<CR>
map <Leader>d :bd<CR>
map <Leader>j :bn<CR>
map <Leader>k :bp<CR>

" Better searching
set hlsearch
set ignorecase
set smartcase

" Open split windows
set splitbelow
set splitright
noremap <C-Down> :sp<CR>
noremap <C-Up> :sp<CR><C-W><C-K>
noremap <C-Right> :vsp<CR>
noremap <C-Left> :vsp<CR><C-W><C-H>

" Navigate split windows
noremap <C-J> <C-W><C-J>
noremap <C-K> <C-W><C-K>
noremap <C-L> <C-W><C-L>
noremap <C-H> <C-W><C-H>

" Allow buffers to be backgrounded
" even if they have unsaved changes
set hidden

" RSpec.vim mappings
if executable("spring")
  let g:rspec_command = "!spring rspec {spec}"
endif
map <Leader>sf :call RunCurrentSpecFile()<CR>
map <Leader>ss :call RunNearestSpec()<CR>
map <Leader>sl :call RunLastSpec()<CR>
map <Leader>sa :call RunAllSpecs()<CR>

" Open files
map <Leader>o :!open %<CR>

" Quicker opening and closing of folds
map <Leader><Space> za

" Mark long lines
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.\+/
